/// Utility for generating titles from note content using smart heuristics
class TitleGenerator {
  /// Generate a concise title from note content
  ///
  /// Uses heuristics to extract meaningful title:
  /// - Extracts first sentence
  /// - Limits to 6-8 words
  /// - Removes formatting and special characters
  /// - Proper capitalization
  static String generateTitle(String plainText) {
    if (plainText.trim().isEmpty) {
      return '';
    }

    // Split into sentences (by period, exclamation, question mark, or newline)
    final sentences = plainText.split(RegExp(r'[.!?\n]+'));

    // Get first non-empty sentence
    String firstSentence = '';
    for (final sentence in sentences) {
      final trimmed = sentence.trim();
      if (trimmed.isNotEmpty) {
        firstSentence = trimmed;
        break;
      }
    }

    if (firstSentence.isEmpty) {
      return '';
    }

    // Split into words
    final words = firstSentence.split(RegExp(r'\s+'));

    // Take first 6-8 words (whichever makes more sense)
    final maxWords = 8;
    final selectedWords = words.take(maxWords).toList();

    // If we stopped mid-sentence and there are more words, try to end at a natural break
    if (words.length > maxWords) {
      // Remove trailing incomplete words if needed
      final title = selectedWords.join(' ');

      // If title is very short (< 20 chars), allow a few more words
      if (title.length < 20 && words.length > maxWords) {
        selectedWords.addAll(words.skip(maxWords).take(2));
      }
    }

    String title = selectedWords.join(' ');

    // Clean up the title
    title = _cleanTitle(title);

    // Ensure proper capitalization
    title = _capitalizeTitle(title);

    // Limit total length to 60 characters
    if (title.length > 60) {
      title = '${title.substring(0, 57)}...';
    }

    return title;
  }

  /// Clean up title by removing special characters and formatting
  static String _cleanTitle(String title) {
    // Remove markdown formatting
    title = title.replaceAll(RegExp(r'[*_`~#]'), '');

    // Remove multiple spaces
    title = title.replaceAll(RegExp(r'\s+'), ' ');

    // Remove leading/trailing punctuation
    title = title.replaceAll(RegExp(r'^[^\w\s]+|[^\w\s]+$'), '');

    return title.trim();
  }

  /// Capitalize first letter of title
  static String _capitalizeTitle(String title) {
    if (title.isEmpty) return title;

    // Capitalize first character
    return title[0].toUpperCase() + title.substring(1);
  }

  /// Check if a title appears to be auto-generated
  /// (Used to determine if we should regenerate it)
  static bool looksAutoGenerated(String title, String plainText) {
    if (title.trim().isEmpty || plainText.trim().isEmpty) {
      return true;
    }

    // If title is exactly at the start of plainText, likely auto-generated
    final normalizedTitle = title.trim().toLowerCase();
    final normalizedText = plainText.trim().toLowerCase();

    return normalizedText.startsWith(normalizedTitle);
  }
}
